services:
  - type: web
    name: mi-varotra
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: mi-varotra-db
          property: connectionString
      - key: APP_KEY
        value: base64:SU7pkYW5M9s0kEFcEE2TozhF6gw9MR/o4qrDrp63lyE=
      - key: SESSION_DRIVER
        value: cookie
      - key: NODE_VERSION
        value: 20

databases:
  - name: mi-varotra-db
    plan: free
    databaseName: mivarotra
    user: mivarotra
